services:
  mdm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mdm
    ports:
      - "2232:2232"
    volumes:
      - ./data:/app/data
      - ./templates:/app/templates
      - ./static:/app/static
